version: '3.7'

services:
  nginx-web: 
    image: nginx:stable-alpine3.19-slim
    container_name: nginx-web
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf